import { test, expect } from "@playwright/test";
import golden from "./parity_golden.json";

/**
 * KEYSTONE TEST (plan §7). The browser (Pyodide) must produce the same
 * numbers as the CPython core_api oracle. parity_golden.json is generated by
 * scripts/gen_parity_golden.py running core_api under CPython; here we run the
 * identical params through the in-browser path and assert metrics within 1e-6.
 *
 * If this fails, browser != server and the build must not ship.
 */

const TOL = 1e-6;

type GoldenCase = {
  fn: string;
  params: Record<string, unknown>;
  metrics: Record<string, number>;
};

test("browser compute matches CPython oracle within 1e-6", async ({ page }) => {
  await page.goto("/dashboard");

  // Wait for the in-browser engine to finish booting.
  await page.waitForFunction(
    () =>
      (window as unknown as { __optimarket?: { getBootStatus: () => { phase: string } } })
        .__optimarket?.getBootStatus().phase === "ready",
    null,
    { timeout: 150_000 },
  );

  for (const [name, c] of Object.entries(
    golden as Record<string, GoldenCase>,
  )) {
    const metrics = await page.evaluate(async (params) => {
      const api = (
        window as unknown as {
          __optimarket: {
            runOptimizer: (p: unknown) => Promise<{ metrics: Record<string, number> }>;
          };
        }
      ).__optimarket;
      const res = await api.runOptimizer(params);
      return res.metrics;
    }, c.params);

    for (const [k, expected] of Object.entries(c.metrics)) {
      expect(
        Math.abs(metrics[k] - expected),
        `${name}.${k}: browser=${metrics[k]} oracle=${expected}`,
      ).toBeLessThan(TOL);
    }
  }
});
